# Type stubs for torch.nn
# Covers only the symbols used by this project.

from collections.abc import Iterator
from typing import Any

from .. import Tensor

class Module:
    def __init__(self) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def parameters(self, recurse: bool = True) -> Iterator[Tensor]: ...
    def forward(self, *args: Any, **kwargs: Any) -> Any: ...

class Sequential(Module):
    def __init__(self, *args: Module) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...

class Linear(Module):
    in_features: int
    out_features: int
    def __init__(self, in_features: int, out_features: int, bias: bool = True) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...

class Tanh(Module):
    def forward(self, input: Tensor) -> Tensor: ...
