# Type stubs for matplotlib.axes._axes (private submodule)
# Pyright resolves seaborn's return type as matplotlib.axes._axes.Axes.

from typing import Any

from .lines import Line2D

class Axes:
    def plot(self, *args: Any, **kwargs: Any) -> list[Line2D]: ...
    def set(self, **kwargs: Any) -> list[Any]: ...
    def set_title(self, label: str, **kwargs: Any) -> Any: ...
    def set_xlabel(self, xlabel: str, **kwargs: Any) -> Any: ...
    def set_ylabel(self, ylabel: str, **kwargs: Any) -> Any: ...
    def legend(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_xlim(self, *args: Any, **kwargs: Any) -> tuple[float, float]: ...
    def set_ylim(self, *args: Any, **kwargs: Any) -> tuple[float, float]: ...
