# Type stubs for torch 2.10.0
# Covers only the symbols used by this project.

from collections.abc import Iterable, Sequence
from typing import Any, overload

import numpy as np

from . import cuda as cuda
from . import distributions as distributions
from . import nn as nn
from . import optim as optim

class device:
    def __init__(self, type: str, index: int | None = None) -> None: ...

class Generator: ...

class Size(tuple[int, ...]):
    def __new__(cls, iterable: Iterable[int] = ...) -> Size: ...

class Tensor:
    # Casting / conversion
    def float(self) -> Tensor: ...
    def numpy(self, *, force: bool = False) -> np.ndarray[Any, Any]: ...
    def item(self) -> int | float: ...

    # Shape manipulation
    def squeeze(self, dim: int | None = None) -> Tensor: ...

    # Autograd
    def backward(
        self,
        gradient: Tensor | None = None,
        retain_graph: bool | None = None,
        create_graph: bool = False,
        inputs: Sequence[Tensor] | None = None,
    ) -> None: ...

    # Indexing
    def __getitem__(self, index: Any) -> Tensor: ...

    # Arithmetic
    def __add__(self, other: Tensor | int | float) -> Tensor: ...
    def __radd__(self, other: Tensor | int | float) -> Tensor: ...
    def __sub__(self, other: Tensor | int | float) -> Tensor: ...
    def __rsub__(self, other: Tensor | int | float) -> Tensor: ...
    def __mul__(self, other: Tensor | int | float) -> Tensor: ...
    def __rmul__(self, other: Tensor | int | float) -> Tensor: ...
    def __neg__(self) -> Tensor: ...
    def __truediv__(self, other: Tensor | int | float) -> Tensor: ...

# --- Module-level functions ---

def from_numpy(ndarray: np.ndarray[Any, Any]) -> Tensor: ...
def manual_seed(seed: int) -> Generator: ...
def tensor(
    data: Any, *, dtype: Any = None, device: device | str | None = None, requires_grad: bool = False
) -> Tensor: ...
def log(input: Tensor) -> Tensor: ...
def exp(input: Tensor) -> Tensor: ...
def stack(tensors: Sequence[Tensor], dim: int = 0) -> Tensor: ...
@overload
def sum(input: Tensor) -> Tensor: ...
@overload
def sum(input: Tensor, dim: int | tuple[int, ...], keepdim: bool = False) -> Tensor: ...
def set_default_device(device: device | str | None) -> None: ...
